[package]
name = "voting-dapp"
version = "1.0.0"
authors = []

[addresses]
P2PTutoring = "0x3fab6f32dc2dff3ddfd8a03177e2a5c9c0cf0357e8e4494e88de4a600adb8b54"

[dev-addresses]

[dependencies]
aptos-framework = { git = "https://github.com/aptos-labs/aptos-core", rev = "main" }

[dev-dependencies]
